name: Publish to RubyGems

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0

    - name: Set Access to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEM_API_KEY}}"

    - name: Publish to RubyGems
      run: |
        bundle install
        bundle exec rake vendor
        bundle exec rspec
        bundle exec rake publish_gem